### ISSUE TITLE
GREI 2: HDV Task: Support Multiple DataCite Providers

### ISSUE THREAD

**Issue by cmbz** [IQSS/dataverse-pm#132]
## Overview
Dataverse currently allows DataCite Repository credentials to be specified at the instance/installation level. This means that all datasets will be part of the same DataCite Repository and have the same prefix. Currently, it is not possible to specify different credentials for different Dataverse collections. Because only one set of DataCite Repository credentials can be specified, all DOIs must be managed by the administrator of the instance.

A growing use case for Dataverse collections is to serve as institutional repositories within a single Dataverse installation. With this setup, institutions should be able to manage their own DataCite DOIs. This proposal outlines the work required to allow multiple sets of DataCite repository credentials to be active within a single Dataverse instance.

Source: [Proposal: Collection-level specification of DataCite repository credentials](https://docs.google.com/document/d/1WkNmuNKAvPkPZJDOrFPujDoD11LeFb1Vrbcyylkc7DE/edit?usp=sharing)

### Background
Four Dataverse installations serve as use cases for this task: (see [Multiple DataCite credentials in Dataverse](https://docs.google.com/document/d/1WkNmuNKAvPkPZJDOrFPujDoD11LeFb1Vrbcyylkc7DE/edit?usp=sharing))

1. Universidad del Rosario (El Repositorio de datos de investigación)
2. Consortio Madrono
3. Texas Data Repository @ Texas Digital Library
4. Borealis (formerly Scholars Portal Dataverse)

## Tasks
- [x] Define and prioritize work 
- [x] Implement Multiple DataCite credentials in Dataverse

## Issues
- https://github.com/IQSS/dataverse/issues/2943
- https://github.com/IQSS/dataverse/issues/3623
- https://github.com/IQSS/dataverse/pull/8674
- https://github.com/IQSS/dataverse/pull/10234

## Related
- https://github.com/IQSS/dataverse/pull/10391

## Resources
- https://github.com/IQSS/dataverse-pm/issues/124
- https://github.com/IQSS/dataverse-pm/issues/97
- https://github.com/IQSS/dataverse-pm/issues/116
- [APPROVED - NIH GREI Coopetition Plan Year 3](https://docs.google.com/document/d/1XTJSOfUlg06WYGXe3URVFH6VaPMkBNPqVZgrsqOrbc0/edit?usp=sharing)
- [DRAFT: Year 3 Realignment Proposal Plan](https://docs.google.com/document/d/1ADskSIH6T4LGt8Lz4eibzNOq4lnzGNxu/edit?usp=drive_link&ouid=102516728224230315414&rtpof=true&sd=true) (Document)
- [NIH GREI Aim 2 Yearly Progress (Year 2)](https://docs.google.com/document/d/1kwkXucTlbEMl82dCoAu-l80MVRKzdFQb5g88B2g5K4U/edit?usp=sharing) (Document, Deprecated)

**Comment by pdurbin** [comment]
Related:

- https://github.com/IQSS/dataverse/issues/3623

**Comment by qqmyers** [comment]
Could be closed by https://github.com/IQSS/dataverse/pull/10234

**Comment by qqmyers** [comment]
[#10370](https://github.com/IQSS/dataverse/pull/10370) fixes one problem with backward compatibility after the main #10234 PR was merged. This Issue should close after 10370 is merged.

**Comment by cmbz** [comment]
## March 2024
- TBD

**Comment by cmbz** [comment]
2024/03/20
- Closing this tracking issue as all defined and scoped work is now complete
