### ISSUE TITLE
NIH AIM:3 YR:2 TASK:2  | 2.3.2  | Research and discovery phase for containers and research objects support

### ISSUE THREAD

**Issue by mreekie** [IQSS/dataverse-pm#15]
From discussions with Mahmood

The workflow work for the year 1 deliverables  has been release in 5.12.
What is needed is to needed is to add support for additional use cases specific to the biomedical fields.

* Odum Institute computational workflow was reviewed.
* Codemeta workflow was reviewed.
* [BioSchema](https://bioschemas.org/profiles/ComputationalWorkflow/1.0-RELEASE) was reviewed

The terms for the MVP were chosen.

* This is [the Computation Workflow Metadata Planning](https://docs.google.com/spreadsheets/d/1vByU0uGBU-jHEgvXeAs-zMVc7zPt8PiZ4FGoHpKnJy4/edit#gid=1849651392) Sheet
* On this sheet, everything marked MVP has been implemented in 5.12
* We can use this same sheet to go back and choose to implement additional BioMedcal terms.

The container work is also open.

* We can engage with Mahmood to do this.
* Next step here is to touch base with the person from the community who is working on this already (@pdurbin) mentioned the connection today.

**Part of this sequence of deliverables:**
1.3.1 | 3 | Support software metadata | 5
1.3.2 | 3 | Research and discovery phase for biomedical workflows support | 5
2.3.1 | 3 | Support biomedical workflows | 5
2.3.2 | 3 | Research and discovery phase for containers and research objects support | 5
3.3.1 | 3 | Support containers and research objects  | 10
4.3.1 | 3 | Apply container, RO, workflows support to a few NIH-funded projects | 10

┆Issue is synchronized with this [Smartsheet row](https://app.smartsheet.com/sheets/3PXV7GPQcQ769PMhmJvPGr5RcCmgG65VgmFHJv21?rowId=52728863123332) by [Unito](https://www.unito.io)

**Comment by mreekie** [comment]
Febrary 2023 update

 (2.3.1) Initial meeting was held. Work will focus on a new metadata block 
which was added as part of (1.3.2). The next step is finalizing the metadata 
terms. This activity will continue in year 2 as planned. 
● (2.3.2) We recently implemented an intermediate solution that provides the 
ability to run data analysis in an

**Comment by mreekie** [comment]
March Update

We recently implemented a solution that provides the ability to run data analysis in an external container using [Binder](https://github.com/IQSS/dataverse/pull/9341). We [improved](https://groups.google.com/g/dataverse-community/c/yl31eO-uHUA/m/h0JSC0vWAQAJ) the code underlying Binder (repo2docker) to allow it to download tabular data from Dataverse in its original format (e.g. Stata rather than an archive-friendly tab separated values format).

**Comment by pdurbin** [comment]
> Febrary 2023 update
> 
>     * (2.3.1) Initial meeting was held.

@mreekie any notes from the initial meeting?

**Comment by cmbz** [comment]
May 2023 Update: An initial meeting was held with interested stakeholders on 2023/05/05 to discuss requirements for supporting research objects beyond datasets and preliminary design approaches including an option for creating a Dataverse database entry for object types. Follow-up discussions will be planned.

**Comment by cmbz** [comment]
2024/01/03: Closing, work will be tracked here: https://github.com/IQSS/dataverse-pm/issues/146
