### ISSUE TITLE
NIH AIM:3 YR:2 TASK:1  | 2.3.1 | Support biomedical workflows

### ISSUE THREAD

**Issue by mreekie** [IQSS/dataverse-pm#16]
Discussion with Mahmood.

* Implementation will not be a challenge.
* When computational workflow was done, we added a new metadata block.
* The metadata terms need to be reviewed.
* In upload page, not every field for code-meta is exposed.
* In a meeting with Phillip, Oliver, Ana, Julian - finalize the metadata terms.
* Ensure that what is included is correct and theen this can be merged.

Predecessor:
[1.3.2 | 3 | Research and discovery phase for biomedical workflows support | 5](https://github.com/IQSS/dataverse-pm/issues/11)

**Part of this sequence of deliverables:**
1.3.1 | 3 | Support software metadata | 5
[1.3.2 | 3 | Research and discovery phase for biomedical workflows support | 5](https://github.com/IQSS/dataverse-pm/issues/11)
2.3.1 | 3 | Support biomedical workflows | 5
2.3.2 | 3 | Research and discovery phase for containers and research objects support | 5
3.3.1 | 3 | Support containers and research objects  | 10
4.3.1 | 3 | Apply container, RO, workflows support to a few NIH-funded projects | 10

┆Issue is synchronized with this [Smartsheet row](https://app.smartsheet.com/sheets/3PXV7GPQcQ769PMhmJvPGr5RcCmgG65VgmFHJv21?rowId=7359407220844420) by [Unito](https://www.unito.io)

**Comment by mreekie** [comment]
Febrary 2023 update

-  (2.3.1) Initial meeting was held. Work will focus on a new metadata block 
which was added as part of (1.3.2). The next step is finalizing the metadata 
terms. This activity will continue in year 2 as planned. 
-  (2.3.2) We recently implemented an intermediate solution that provides the 
ability to run data analysis in an external container using Binder. Few minor 
fixing done during this month.

**Comment by mreekie** [comment]
March Update:

(2.3.1) We were able to get a small head start on 2.3.1 (3%) in year 1. Initial meeting was held. Work will focus on a new metadata block which was added as part of (1.3.2). The next step is finalizing the metadata terms. This activity will continue in year 2 as planned.

**Comment by cmbz** [comment]
2024/01/03: Closing, work will be tracked here: https://github.com/IQSS/dataverse-pm/issues/149 and here: https://github.com/IQSS/dataverse-pm/issues/146
