### ISSUE TITLE
Epic: GREI Repository Flow Chart Task Group

### ISSUE THREAD

**Issue by cmbz** [IQSS/dataverse-pm#186]
## Overview
-  See: https://github.com/NIH-GREI/grei-pm/issues/35

**Comment by cmbz** [comment]
## January 2024
- Building New Resources: Flowchart Task Group met with Vivli and HMS to discuss repository flowchart creation.

**Comment by cmbz** [comment]
## Status: March 2024
-

**Comment by cmbz** [comment]
## Status: April 2024
- No updates this month
- Task group will be sunsetted when the related blog post is finalized and published.

**Comment by sbarbosadataverse** [comment]
## Status: May 2024
- Accessibility review has taken place and color upgrades are being added today. Deadline to publish is Monday morning.

**Comment by cmbz** [comment]
## Status: June 2024
- Pending

**Comment by cmbz** [comment]
## Status: July 2024
- Pending

**Comment by sbarbosadataverse** [comment]
All associated GREI tasks for this issue are complete. Closing.
