### ISSUE TITLE
Epic: Support the  5 core persistent identifiers in Dataverse

### ISSUE THREAD

**Issue by mreekie** [IQSS/dataverse-pm#19]
This deliverable defines our support for the 5 core pids.  

For most of the 5, we offer support already.
- we will document what that support is.

For the others:
- We will define how we intend to support it right now.
- We will implement that support.

This came out of our meeting on Jan 31st, 2023. We discussed how we are going to define our support for each of these PIDs through a definition of "we support this type of data", "for this type of field"

![image](https://user-images.githubusercontent.com/47538814/217355188-2cda0013-123d-4dcb-a14b-76c1103d1623.png)

Includes...
- https://github.com/IQSS/dataverse/issues/9150
- https://github.com/IQSS/dataverse/issues/9151
- https://github.com/IQSS/dataverse/issues/7285
- https://github.com/IQSS/dataverse/issues/9370

---
Just a reminder that this is a "deliverable" issue. It does not go on the sprint board.  It's a group of other issues that represent the delivery of some objective for us to get to or functionality delivered.

**Comment by cmbz** [comment]
Develop a plan to address the work needed to move this epic forward. Note: re-architecture work should take into account what is planned here (e.g., process used to change UI for metadata fields)
- [ ] Identify & review different metadata fields related to the different PIDs
- [ ] Scope work
- [ ] Coordinate with relevant NIH-GREI subcommittees/working groups as needed (their recommendations may inform our approach)
- Contributors include: Julian, Sonia, Gustavo

**Comment by cmbz** [comment]
2023/09/25: Will require a proposal to scope the investigation and identify a set of tasks. We will need to split this issue into some sub-issues that can be sized, prioritized, and implemented.

**Comment by cmbz** [comment]
2024/01/08
- Converted issue into a epic during the prioritization meeting. We (@cmbz, @sbarbosadataverse, @jggautier and @scolapasta) need to make a plan to address the tasks outlined here: https://github.com/IQSS/dataverse-pm/issues/19#issuecomment-1530046654

**Comment by jggautier** [comment]
The NIH-GREI's metadata subcommittee and the Dataverse UX WG have done work to address the tasks outlined at https://github.com/IQSS/dataverse-pm/issues/19#issuecomment-1530046654, are continuing to work on those tasks, and that work is being tracked in other GitHub issues.

I'm going to close this GitHub issue.

**Comment by cmbz** [comment]
@jggautier are [these the additional issues](https://github.com/IQSS/dataverse-pm/issues/195) that you/UX working group are addressing? If not, could you add them to the epic, please, and add a description to the issue itself? Thanks.

**Comment by jggautier** [comment]
Hi @cmbz. Yeah the UX WG is planning to address part of https://github.com/IQSS/dataverse-pm/issues/127 during its second design sprint about improving metadata related to related research objects, like related publications that often have DOIs and Handles.

The first design sprint we're in the middle of now involves improving support of RORs and ORCIDs for describing people and organizations associated with deposits. I've been using the GitHub issue at https://github.com/IQSS/dataverse-pm/issues/127 and the "Epics and Issues" listed there to describe that work.
