### ISSUE TITLE
Spike: During some sprints we end the sprint with a few days with QA empty

### ISSUE THREAD

**Issue by mreekie** [IQSS/dataverse-pm#2]
This was  a top 3 out of the retrospective, but we didn't have time to discuss it very deeply there. 
I'm taking a shot at it here.

This has not gotten the discussion it needs.
- is this referring to the idea that we could have done more PRs?
- or are folks feeling like QA wasn't busy enough?
- or are we sizing our issues too big so that there are gaps?

This is important as a team discussion as well because it touches on the idea of a the pull model.  Does the QA team feel it had enough work? QA pulls in the same way dev does.

**Comment by kcondon** [comment]
I guess I'm interested in whether we also plan to track or address when individual developers are ever not assigned to something. Being the only one in QA, that seems equivalent.

**Comment by mreekie** [comment]
Just a quick status update
- I had discussions with Kevin and Jim, and separately with Stefano.

It sounds like we're leaning towards:
- Keep sizing issues holistically: The size includes start to finish including time through QA.
- We are going to count the points at the end of the sprint as those issues that cleared review and are waiting for QA.

The model behind this is that we can simplify the workloads on QA and the dev team as being sine waves that cancel each other out.  

At the beginning of a sprint, the dev team is in develop mode, while QA can be finishing up the QA items from the last sprint. In the long term, all else being equal the work will balance out.  

![image](https://user-images.githubusercontent.com/47538814/213564370-978fae4c-dcae-43fd-8a0f-3ef2b8d5f275.png)

**Comment by mreekie** [comment]
The second thing is that we are going to try out a "ready for QA" column.
This is not a direct part of the solution. the reason is that it makes it easier to see at a glance what is in QA versus the backlog in the same way that we can see what's waiting for review versus being in review.

**Comment by mreekie** [comment]
This'll stay open until the end of this sprint when the changes are introduced for the next sprint so that any last minute changes can be recorded.

**Comment by mreekie** [comment]
We spoke about this yesterday during the daily standup.
We've implemented changes as agreed by the team.
