### ISSUE TITLE
Project: Establish Harvard Pre-Peer Review Program (PPR) Support

### ISSUE THREAD

**Issue by cmbz** [IQSS/dataverse-pm#204]
## Overview
- This project tracks the work needed to This proposal describes a plan to shift the ongoing development and maintenance for the [Harvard Peer Pre-Review Program](https://pre-review.iq.harvard.edu/index.php/iqss) (HPPRP) software from a temporarily assigned [IQSS Sid](https://scholar.harvard.edu/sid/node/637315) developer to on [Dataverse Project](https://dataverse.org/) developer and or DevOps engineer with relevant expertise.
- Once the tasks are complete, this _Project_ will be closed and a new on-going _Monitoring_ issue opened for resource tracking/allocation.

## Timeline and Tasks
- See also: [Proposal: Provide Ongoing Technical Support for the Harvard Peer Pre-Review Program](https://docs.google.com/document/d/1cBT4BLglxTzzlZr2W0Q0MF6WlduU3r3UwM8e_wcJM9g/edit?usp=sharing). Note that proposal timeline is out of date; refer to the timeline in this issue instead.

### February 2024: Develop support plan and developer onboarding
- [x] Develop HPPRP support plan
  - @cmbz 
- [x] Developer onboarding
  - @abujeda
  - @jp-tosca 
- [x] Review support plan
  - @siacus 
  - @hlmshtj-dan
  - Andrew Juraschek

### March 2024: Finalize plan and begin transition
- [x] Finalize support plan
  - @siacus 
  - @hlmshtj-dan
  - Andrew Juraschek

### April 2024 - September 2024: Implement test server and continue support and monitoring
- [x] Develop development and DevOps transition plan (with team input)
  - @hlmshtj-dan 
  - @cmbz 
- [x] Investigate technical requirements for migrating the HPPRP OJS test server, including stand up of a mail server. May involve additional Dataverse Project resources
  - @abujeda
  - @hlmshtj-dan
  - @stevenwinship 
- [x] Schedule and resource migration of HPPRP OJS test server. May involve additional Dataverse Project resources
  - @hlmshtj-dan
  - @cmbz 
  - @stevenwinship 
- [x] Implement PPR project management and monitoring mechanism
  - See https://github.com/IQSS/dataverse-pm/issues/210
  - [x] Investigate migration from Smartsheets to GitHub project
  - @cmbz 
  - @hlmshtj-dan
- [x] Develop HPPR developer and sysop documentation
  - @jp-tosca 
  - @stevenwinship 
  - @abujeda (provide notes and recommendations)
- [x] Active HPPRP support begins
  - @abujeda (50%)
  - @jp-tosca (50%)
  - @stevenwinship 
- [x] Review project progress
  - Project team members
- [x] Implement OJS test server, dependent on the timeline
  - Aday Bujeda
  - @stevenwinship 
- [x] Review project progress
  - Project team members

### July 2024: Transition complete
- [x] Final transition to Dataverse Project team support
  - @jp-tosca 
  - @stevenwinship (as needed)
- [x] Final transition to HPPRP resource monitoring
  - @cmbz 
- [x] Review project progress
  - Project team members

### August 2024
- [x] Complete miscellaneous project close-out tasks

## Related
- https://github.com/IQSS/dataverse-pm/issues/210
- https://github.com/IQSS/dataverse-pm/issues/180

## Resources
- [PPR Engineering Transition from Aday to Dataverse Team](https://docs.google.com/document/d/1wM-CMfVeFgO0AJvX_BuiNWKe1EJE9_K4I466sOorLXg/edit?usp=sharing)
- [Proposal: Provide Ongoing Technical Support for the Harvard Peer Pre-Review Program](https://docs.google.com/document/d/1cBT4BLglxTzzlZr2W0Q0MF6WlduU3r3UwM8e_wcJM9g/edit?usp=sharing)
- [HPPR Support Project Running Notes](https://docs.google.com/document/d/1IutgSPBfjJm74cbiMmySeyIF6o6kC8ccB7Hh-qy2DYo/edit?usp=sharing)

**Comment by cmbz** [comment]
## March 2024
- TBD

**Comment by cmbz** [comment]
## April 2024
- TBD

**Comment by cmbz** [comment]
## May 2024
- TBD

**Comment by cmbz** [comment]
## Status: June 2024
- Pending

**Comment by hlmshtj-dan** [comment]
> ## May 2024
> * TBD

Hi, here's the markdown for the OJS workflow documentation: https://github.com/IQSS/dataverse-pm/blob/main/OJS%20Workflow%20Documentation.md. Please let me know if this looks OK to you, @stevenwinship @jp-tosca

**Comment by cmbz** [comment]
## Status: August 2024
- Pending

**Comment by cmbz** [comment]
## Status: September 2024
- Pending

**Comment by cmbz** [comment]
## Status: FY25 Summary
- Pending
