### ISSUE TITLE
Epic: GREI: Community Engagement  - Planning Unit

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse-pm#207]
- See:  https://github.com/NIH-GREI/grei-pm/issues/119
- Related: [GREI Community Engagement Label](https://github.com/NIH-GREI/grei-pm/issues?q=is%3Aissue+is%3Aopen+label%3A%22GREI%3A+Community+Engagement%22)

**Comment by sbarbosadataverse** [comment]
## 2024 May Update:
- Planning meeting to confirm deliverables (Marketing plan, upcoming conferences, and flowchart publishing to incorporate into Poster)

**Comment by cmbz** [comment]
## Status: June 2024
- Pending

**Comment by cmbz** [comment]
## Status: July 2024
- Pending

**Comment by cmbz** [comment]
## Status: September 2024
- Pending
