### ISSUE TITLE
NIH GREI Working Groups

### ISSUE THREAD

**Issue by mreekie** [IQSS/dataverse-pm#21]
This is going to be where I collect the monthly updates that go to the NIH
[Link to Backlog Page](https://github.com/orgs/IQSS/projects/32/views/24)

┆Issue is synchronized with this [Smartsheet row](https://app.smartsheet.com/sheets/3PXV7GPQcQ769PMhmJvPGr5RcCmgG65VgmFHJv21?rowId=4399423134623620) by [Unito](https://www.unito.io)

**Comment by cmbz** [comment]
2023/12/19: Closing; monitoring GREI working groups elsewhere.
