### ISSUE TITLE
GREI 7: HDV Task - DataTags: Locate existing DataTags documentation

### ISSUE THREAD

**Issue by cmbz** [IQSS/dataverse-pm#245]
## Overview
Locate existing DataTags documentation, demos, and mockups beyond the currently known document: [Sharing Sensitive Data with Confidence: The Datatags System](https://scholar.harvard.edu/files/mercecrosas/files/techsci-datatags-sweeneycrosasbarsinai.pdf)

## Deliverables
- [Sharing Sensitive Data with Confidence: The Datatags System](https://scholar.harvard.edu/files/mercecrosas/files/techsci-datatags-sweeneycrosasbarsinai.pdf)
-  [Design Considerations for Handling Sensitive Data in Dataverse](https://docs.google.com/document/d/1gIMCm4iou5UPgm6OiIftuQIyoWWOIwaXpaY39o_3K74/edit?usp=sharing)
- [Sharing Sensitive Data with Confidence: The Datatags System](https://scholar.harvard.edu/files/mercecrosas/files/techsci-datatags-sweeneycrosasbarsinai.pdf)
- [Design Considerations for Handling Sensitive Data in Dataverse](https://docs.google.com/document/d/1gIMCm4iou5UPgm6OiIftuQIyoWWOIwaXpaY39o_3K74/edit?usp=sharing)
- [DataTags_legal_docs](https://drive.google.com/drive/folders/1o-8mz9R9x4BRzGG8cw2F4cq5erly05Ne?usp=drive_link) (Google Drive)
- [DataTags](https://drive.google.com/drive/folders/0B5iL_lNzaDucb3VvRXFBa0o2aEk?resourcekey=0-8vVLZPS4q8xVOZF2NXSqaA&usp=drive_link) (Google Drive)
- https://github.com/IQSS/DataTaggingLibrary 
- https://privacytools.seas.harvard.edu/datatags
- https://privacytools.seas.harvard.edu/datatags-dataverse
- https://techscience.org/a/2015101601/ 
- https://irods.org/uploads/2014/06/IRODSMeeting-DataverseDataTags.pdf 
- https://www.bitss.org/wp-content/uploads/2015/12/OPEN-DATA-AND-PROTECTION-OF-RESEARCH-SUBJECTS-Merce-Crosas.pdf 
- https://dataverse.org/publications/datatags-data-handling-policy-spaces-and-tags-language

## Resources
- https://github.com/IQSS/dataverse-pm/issues/124
- https://github.com/IQSS/dataverse-pm/issues/121
- https://github.com/IQSS/dataverse-pm/issues/197

**Comment by qqmyers** [comment]
[This doc](https://docs.google.com/document/d/1gIMCm4iou5UPgm6OiIftuQIyoWWOIwaXpaY39o_3K74/edit?usp=sharing) has a summary and some links to earlier materials.

**Comment by cmbz** [comment]
## Status: May 2024
-

**Comment by cmbz** [comment]
2024/05/23: Closing issue, we can update issue once we hear from LaTanya re. the website.
