### ISSUE TITLE
Collection: Keep track of list of issues that we want to address as part of 1.4.1

### ISSUE THREAD

**Issue by mreekie** [IQSS/dataverse-pm#25]
The first step was to figure out what has already been done by the dataverse team and by the community towards this aim and what still remains to be done.  Leonid's conclusions at [the conclusion of  Issue 8574](https://github.com/IQSS/dataverse-pm/issues/24) does that.

This Epic tracks the work as proposed by Leonid:

I do believe that the third item under the "definition of done" - "prioritize" - was the actual important part of this spike. I also believe that most of that effort of prioritizing what's important can only be done within the dev. team. I can't think of how anyone outside of it could be more qualified to make these calls. So I'm going to make such an attempt. 
(Note that I'm interpreting the word "prioritizing" as assigning some order of importance to these issues and bugs, what makes sense to fix first and/or what's ready to be worked on vs. what needs more discussion; not as scheduling them for specific sprints, etc.!)

The single most important harvesting issue: (ok, maybe not the most important - but seriously, this should be the first step of any meaningful cleanup of our harvesting implementation; should be fairly easy to wrap up too)
- [x]  https://github.com/IQSS/dataverse/issues/8372

The following issues are important in that fixing them will make harvesting more reliable and robust overall (for example, in the current implementation a *single* missing metadata export that's supposed to be cached is going to break the entire harvesting run). All of the issues on the list below are defined clearly enough that they are ready to be worked on and fixed, without needing to conduct any extra research first. Some of them may be VERY OLD; but they look like something we should fix. 
- [x]  https://github.com/IQSS/dataverse/issues/8484 [backend]
- [ ]  https://github.com/IQSS/dataverse/issues/7940 [backend, api]
- [ ]  https://github.com/IQSS/dataverse/issues/8005 [backend]
- [ ]  https://github.com/IQSS/dataverse/issues/7736 [backend, import]
- [ ]  https://github.com/IQSS/dataverse/issues/3437 [backend]
- [ ]  https://github.com/IQSS/dataverse/issues/3322 [backend]
- [ ]  https://github.com/IQSS/dataverse/issues/8290 [api]
- [ ]  https://github.com/IQSS/dataverse/issues/8289 [backend, ui]

the following 3 issues are basically the same thing - people requesting extra ISO language codes to be added as legitimate controlled vocab. values (this is just a matter of adding extra values to citation.tsv); these are NOT duplicates, different things are being requested to be added in the issues below, but makes sense to get all 3 out of the way at the same time:
- [ ]  https://github.com/IQSS/dataverse/issues/8578 [metadata, import]
- [x]  https://github.com/IQSS/dataverse/issues/8139 [metadata, import]
- [ ]  https://github.com/IQSS/dataverse/issues/8243 [metadata, import]

The following issues are about the DDI exporter producing XML that is not valid under the schema.
- [x] https://github.com/IQSS/dataverse/issues/8701

Similarly, the following issues are requests for changes in how we export DC; I believe these need to be reviewed/discussed, perhaps together? 
- [ ]  https://github.com/IQSS/dataverse/issues/8129 [export]
- [ ]  https://github.com/IQSS/dataverse/issues/7243 [export]

The following issues are proposed changes to the design of the harvesting framework and/or metadata exports. Meaning this is something we probably need to discuss as a team, before we decide that these are good ideas and proceed to implement them. But IMO they are (I opened all of them 😄): 

- [ ]  https://github.com/IQSS/dataverse/issues/8630 [backend]
- [ ]  https://github.com/IQSS/dataverse/issues/8629 [backend]
- [ ]  https://github.com/IQSS/dataverse/issues/5960 [backend]
- [ ]  https://github.com/IQSS/dataverse/issues/8631 [backend]
(ordered by importance, IMO)

There is of course this issue that was opened for figuring out what needs to be added specifically for the NIH/GREI grant: 
- [ ]  https://github.com/IQSS/dataverse/issues/8575
It is obviously super important and should be prioritized too; but it's more of a design discussion and research, rather than something we already can start coding. 

The list above is by no means complete. If an issue is not listed, it does not necessarily mean that it's not important. But the ones that are listed above should be a good subset to start with. 

----

# More Background:

This is in support of:

an NIH grant ["The Harvard Dataverse repository: A generalist repository integrated with a Data Commons"](https://docs.google.com/document/d/1cFK8pdwMKIRZxNs8EZXL1cXmW0ho6Rx9ulCewJ1ZCFI/edit?usp=sharing),
Aim 4: Improve harvesting and packaging standards to share metadata and data across repositories,

## There is a lot packaged into Aim 4

Improved Harvesting via the OAI-PMH standard
Improved support for Bagit
Improved support for Signposting
The scope for this issue is Harvesting via the OAI-PMH standard

## Aim 4:
Improve harvesting and packaging standards to share metadata and data across repositories

Our proposed project will significantly improve the widely-used Harvard Dataverse repository to better support NIH-funded research.

A critical measure of the [GREI program](https://www.iq.harvard.edu/news/dataverse-joins-nih-data-repository-initiative)’s success is to standardize the discoverability across generalist repositories.

To help with this, **we propose to improve the existing harvesting functionality in the Dataverse software based on the Open Archives Initiative Protocol for Metadata Harvesting (OAI-PMH) standard, and coordinate with other repository packaging standards to share or move metadata and data. **

Dataverse already supports the Bags as defined by the Research Data Alliance (RDA) Research Data Repository Interoperability Working Group. Here we proposed to improve the support for Bags, test it for NIH-funded datasets, and explore and define the appropriate standard to use to move the metadata and data across generalist repositories. This will help with a sustainable and succession plan - if one repository cannot support anymore a specific dataset, it will allow to easily move the dataset to another repository without losing any information about the dataset.

Additionally we propose to implement Signposting in the Dataverse software. By adding additional http link headers throughout the application, we can more easily support automated metadata and data discovery in the repository, and allow for other applications and services to more accurately and completely represent the content in the Harvard Dataverse repository.

### Related documents
[Notes on Dataverse Deliverablas for NIH OTA](https://docs.google.com/document/d/1N9xgubVcHb2mQxnCrmusa0M7qVGiVvyvmODc4j4HvQ8/edit?usp=sharing)
[NIH OTA Progress Notes](https://docs.google.com/document/d/1k0XLOqYGCbV1O4eqUtOz67Hk4kXqhv4dKg_juabNVw0/edit?usp=sharing)
[NIH OTA](https://docs.google.com/document/d/1cFK8pdwMKIRZxNs8EZXL1cXmW0ho6Rx9ulCewJ1ZCFI/edit?usp=sharing)
[Exposing and harvesting metadata using the OAI metadata harvesting protocol: A tutoria (2001)](https://arxiv.org/pdf/cs/0106057.pdf)
[Getting Started with BagIt in 2018](https://patchbay.tech/blog/2018/03/14/getting-started-with-bagit-in-2018/)
[NIH OTA](https://docs.google.com/document/d/1cFK8pdwMKIRZxNs8EZXL1cXmW0ho6Rx9ulCewJ1ZCFI/edit?usp=sharing)
[bagit from Library of Congress video](https://www.youtube.com/watch?time_continue=11&v=l3p3ao_JSfo&feature=emb_logo)

**Comment by cmbz** [comment]
**2024/01/29**
- I have updated the following epic with remaining open harvesting issues: https://github.com/IQSS/dataverse-pm/issues/171
- Please follow the new epic to track progress on harvesting issues.
