### ISSUE TITLE
PPR: Development Transition, 2024-05-22 to 2024-06-06

### ISSUE THREAD

**Issue by cmbz** [IQSS/dataverse-pm#256]
## Overview
- PPR-related development tasks performed during Sprint 24, 2024-05-22 - 2024-06-06

## Related
- https://github.com/IQSS/dataverse-pm/issues/210

**Comment by jp-tosca** [comment]
- https://github.com/IQSS/ppr-ojs/pull/5
- https://github.com/IQSS/ppr-ojs/pull/9
