### ISSUE TITLE
PPR: Devops Transition, 2024-05-22 to 2024-06-06

### ISSUE THREAD

**Issue by cmbz** [IQSS/dataverse-pm#257]
## Overview
- PPR-related devops tasks performed during Sprint 24, 2024-05-22 - 2024-06-06

## Related
- https://github.com/IQSS/dataverse-pm/issues/210

**Comment by stevenwinship** [comment]
Added smtp server monitoring script. Monitors and restart service if needed.

**Comment by cmbz** [comment]
Thanks @stevenwinship. Closing as complete.
