### ISSUE TITLE
bklog: Deliverable - As a system integrator, I would appreciate a JSON Schema for validating my dataset JSON before uploading via API

### ISSUE THREAD

**Issue by poikilotherm** [IQSS/dataverse-pm#26]
As a "bklog: Deliverable" This is decomposed into smaller issues.
- Each of the smaller issues gets the label "[D: ImproveJsonValidation](https://github.com/IQSS/dataverse/labels/D%3A%20ImproveJsonValidation)".  
- This issue, the only issue to have both labels (bklog: Deliverable, D: ImproveJsonValidation), will stay in the Dataverse_Global_Backlog project forever.
- It will stay in it's present column until the team feels like the issue has no smaller issues that need need to be broken off in order to resolve this issue
- At that point, this issue stays in the Dataverse_Global_backlog, but changes it's status to: "Clear of the Backlog"

---

This is related to AUSSDA/pyDataverse#48 and to `dvcli` as a CLI tool for Dataverse. (Tagging @skasberger here)
On the Dataverse side of life, this is related to all mighty IQSS/dataverse#6030 and loosley coupled to IQSS/dataverse#4451 (which might make the creation of the schema easier).

When creating a new dataset via the web UI, you will be provided with a nice interface and validation before a dataset is created. What is required, what is available as a field, etc is nicely integrated into the UI both for users and curators.

However, this is not the case with uploading new datasets via API. Before you send a JSON representation, there is not possibility to validate the dataset in terms of metadata schemas, required fields, etc.

It would be nice to provide an API endpoint to retrieve a [JSON Schema](https://json-schema.org/) for a given Dataverse, that contains precise constraints and requirements, what your dataset JSON has to look like and what other fields might be available.

This is useful not only for pre-creation validation, but also for automatic creation of options on command lines (think autocompletion, ncurses interfaces, ...) or [client-side forms](https://json-schema.org/implementations.html#web-ui-generation).

**Comment by mreekie** [comment]
Sizing:
- Oliver mentioned that when he is able to get to the issue creation he'll drop a note here.

**Comment by kcondon** [comment]
Stub issues for next steps, will be fleshed out by Oliver:
1. https://github.com/IQSS/dataverse/issues/9463
2. https://github.com/IQSS/dataverse/issues/9464
3. https://github.com/IQSS/dataverse/issues/9465

**Comment by mreekie** [comment]
Prio:
- This issue is going to be closed based on the creation of the three issues.

**Comment by pdurbin** [comment]
The latest PR to watch:

- https://github.com/IQSS/dataverse/pull/10543
