### ISSUE TITLE
GREI 2: Task 1 - Review proposal, existing GitHub issues related to improving the collection and use of metadata about people and organizations associated with deposits, including use of ROR and ORCID, think about users for validating solution (Understand stage)

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse-pm#275]
## Purpose
- Ensure that everyone working on a solution for improving how Dataverse collects and uses metadata about people and organizations associated with deposits, including the use of ROR and ORCID, has a shared understanding of goals, requirements, opportunities and constraints.
- Ensure that we have users ready to help evaluate the solution during the "Validation stage" of the design sprint.

## Background
- This is the first stage of a design sprint that the The Dataverse UX Working Group is using in order to implement a solution for improving the collection and use of metadata about people and organizations associated with deposits in a way that encourages a shared understanding of goals and more community collaboration around decision making, and prioritizes testing and evaluation by scaling our ability to distribute more of that work.

## Participants
- Lead: Julian Gautier
- Sherry Lake
- Dieuwertje Bloemen

## Resources
- [Rationale for design sprints and plan for design sprint about using ROR and ORCID to improve metadata about people and organizations associated with deposits](https://docs.google.com/document/d/1P39-FzbUXq7kvcLUGko4tCx1k6SS_HqJ1bM6MPrSy8A)
- [Schedule for design sprint for improving metadata about people and organizations](https://docs.google.com/spreadsheets/d/1qbJiMWtWUxMFAGz6kl96sET1UBmvZiPigpNHz1UzQuI)
- [Design Sprint Kit](https://designsprintkit.withgoogle.com)

## Timeline
- Start: 2024-06-17
- End: 2024-06-21

## Tasks
- Review [Proposal: GREI HDV and Dataverse Metadata Support](https://docs.google.com/document/d/1uXk0KTfnZuRH2Iw3OTZEzP6YgV5O6fX2JPRQdWZBiTY)
- Review related GitHub issues listed at [Related GitHub issues and PRs about improving metadata about people, organizations](https://docs.google.com/document/d/1kCI5SZrnWw5F39zmIoSoDhcaWFD-3sZ7ajU-AdyAa1M)
- Review the [plan for sending to DataCite metadata that repositories already collect](https://github.com/IQSS/dataverse/issues/5889#issuecomment-2025510299) and the discussion in [the related pull request](https://github.com/IQSS/dataverse/pull/10615)
- Think about which types of users should help test the redesign that we all settle on and how to recruit users in their communities for testing, accounting for when we’ve planned to start usability testing (see week 4 of [the schedule](https://docs.google.com/spreadsheets/d/1qbJiMWtWUxMFAGz6kl96sET1UBmvZiPigpNHz1UzQuI))

**Comment by cmbz** [comment]
## Status: June 2024
- Pending
