### ISSUE TITLE
bklog: Deliverable - Upgrade to Payara 6 and from EE 8 to EE 10 (Placeholder issue)

### ISSUE THREAD

**Issue by mreekie** [IQSS/dataverse-pm#28]
The actual bklog issue is:  [bklog: Deliverable - Upgrade to Payara 6 and from EE 8 to EE 10 (end of Payara 5 Community Edition security patches Q2/2022) #8305](https://github.com/IQSS/dataverse/issues/8305)

It could not be moved over to this repo because it's got attached PRs.

**Comment by pdurbin** [comment]
The upgrade to Payara 6 and Jakarta EE 10 was done in this PR:

- https://github.com/IQSS/dataverse/pull/9685

Closing.
