### ISSUE TITLE
Deliverable: Slow response for datasets with high number of files

### ISSUE THREAD

**Issue by mreekie** [IQSS/dataverse-pm#29]
This is an umbrella to be used for all the issues we are seeing related to the title.
What follows is a rough cut of what's been discussed thus far that would need to be done to complete this deliverable.

As a "bklog: Deliverable" This is decomposed into smaller issues.
- Each of the smaller issues gets the label "D: Dataset: large number of files"
- This issue, the only issue to have both labels ("bklog: Deliverable", "D: Dataset: large number of files"), will stay in the Dataverse_Global_Backlog project forever.
- It will stay in it's present column until the team feels like the issue has no smaller issues that need need to be broken off in order to resolve this issue
- At that point, this issue stays in the Dataverse_Global_backlog, but changes it's status to: "Clear of the Backlog"

----

We're talking about this issue in tech hours. Here are some pain points for users:

- Editing the title (or other piece) when there are many files (30,000). The save is prohibitively expensive. Affects depositors. Maybe removing the cascade will help. There are two cascades. We could write tests with the 1000files.zip file vs 1 file. How long to edit the title?
- Slow indexing of a dataset with 30,000 files. Affects sysadmins.
- Only 20 files but many versions. Slow to make the next version. Multiplying affect. Affects depositors. Reindexing is slow?
- ...

Other discussion:

- Does the new zip previewer/downloader help?
- Creating a large JSON for the tree view?
- Let's benchmark and measure perf.
- Check open file handles.

---

@linsherpa thanks for chatting and opening this issue and the ticket.

I'll note that out of the box Dataverse only allows you unzip 1000 files at a time from a zip file: https://guides.dataverse.org/en/5.11.1/installation/config.html#multipleuploadfileslimit ... That's the most official statement I could find about how many files are supported in a single dataset... not a very strong one.

As you mentioned, the practical workaround is probably to double zip the files.

For developers I'll mention that `scripts/search/data/binary/1000files.zip` has 1000 small files we can test with.

Finally, here are some open issues related to large numbers of files in a dataset:

- IQSS/dataverse#8256
- IQSS/dataverse#9763
- IQSS/dataverse#6723
- IQSS/dataverse#5523
- IQSS/dataverse#5283
- IQSS/dataverse#2641
- https://github.com/IQSS/dataverse/issues/9763

**Comment by mreekie** [comment]
Sizing:
- At today's sizing effort we established this issue as the umbrella issue for the larger problem that has been prioritized to fix.
- All of the issues specifically called out in the description have had the label: "D: Dataset: large number of files" added to them.

**Comment by mreekie** [comment]
Prio meeting:
 - Move this over to the "Dataverse Team (Gustavo)" column.
 - The next steps remain the same, but the resulting issues will be ordered by priority in that column.

**Comment by qqmyers** [comment]
https://github.com/IQSS/dataverse/issues/9683 is another related issue.

**Comment by cmbz** [comment]
2024/04/10
- Closing as complete. We will open future issues as needed in context of SPA.
