### ISSUE TITLE
Installation Demo Request: Africa rXiv

### ISSUE THREAD

**Issue by stevenwinship** [IQSS/dataverse-pm#306]
## Overview
- Assist with MVP of DV 
https://github.com/IQSS/dataverse-HDV-Curation/issues/577

**Comment by pdurbin** [comment]
As I mentioned at standup, I'm assigning myself and @donsizemore to this because we are helping at https://help.hmdc.harvard.edu/Ticket/Display.html?id=366961

**Comment by donsizemore** [comment]
@stevenwinship I replied to the RT ticket before I realized it was "your" installation (sorry). I am of course happy to help however you may need.
