### ISSUE TITLE
NIH AIM:5 YR:2 TASK:1 | 2.5.1 | Design and implement usage reports and data citation metrics based on Make Data Count

### ISSUE THREAD

**Issue by mreekie** [IQSS/dataverse-pm#4]
NIH wants each repository to share dataset usage data for datasets that were funded by the NIH.  The NIH wants to see how the datasets that they funded are being used and they want the reporting methodology and statistics to be done in in a standardized way across repositories.

The deliverable for this AIM is begin to provide the usage statistics for datasets funded by the NIH. The pre-requisites for this are the at we've agreed  what we are collecting in a standard fashion with the other repositories and we have implemented the code to make the data collection happen.

**Comment by mreekie** [comment]
This came up at the daily today. 
Jim/Phil discussed next steps.
We don't have a formal issue on it yet, but they want to get together with datacite folks and get the conversation going with them.
The people involved need to include Phil, Leonid and Jim on the dataverse side.
Leonid is out with covid right now so Phil is going to just ping datacite and let them know we are interested in talking.

**Comment by pdurbin** [comment]
Yeah, I just sent @KellyStathis a DM on the GREI Slack. Let's wait for Leonid to get back and figure out internally a good date for us (I'm [polling internally](https://iqss.slack.com/archives/C03R1E7T4KA/p1678137408038169) to see who wants to be there). Then we'll see what day works for Kelly and/or Matt.

**Comment by pdurbin** [comment]
Just a quick update that a few of us met with Kelly and afterward @qqmyers created a great doc to explain how the new tracker probably won't "just work" with Dataverse without some future development. I got approval from Matt and Jim to link to the doc during a GREI Open Metrcis subcommittee meeting so I imagine no one will mind if I link it here: https://docs.google.com/document/d/1cSgRVdOKkY6ouBZyqbDonZtFPNHjvBpu6DOyXHtnL8Y/edit?usp=sharing

**Comment by mreekie** [comment]
March update:

(2.5.1) On March 22, we met with Kelly and Sarla from DataCite about the new Usage Tracker ([notes](https://docs.google.com/document/d/1-MgPP9GvHip9qn-Ct027glrer9cLytkEhiRuXgNqfls/edit?usp=sharing)) and are engaging in a more technical followup with their development team in [a Google doc](https://docs.google.com/document/d/1cSgRVdOKkY6ouBZyqbDonZtFPNHjvBpu6DOyXHtnL8Y/edit?usp=sharing). We are concerned that the tracker won't "just work" without further development. We also started a [thread](https://dataverse.zulipchat.com/#narrow/stream/375707-community/topic/DataCite.20Usage.20Tracker/near/343761047) on the tracker to get input from the community. On March 31 we participated in the GREI Metrics Sub-Committee Meeting ([notes](https://docs.google.com/document/d/1bAkodx8w0PfmapWtwhK87eHcYWtMokNSEDN02nZEUUY/edit?usp=sharing)), where we discussed year 2 plans.

**Comment by cmbz** [comment]
**Update**: See [Using the DataCite MDC Tracker with Dataverse](https://docs.google.com/document/d/1cSgRVdOKkY6ouBZyqbDonZtFPNHjvBpu6DOyXHtnL8Y/edit?usp=sharing) document for relevant discussion about why DataCite's new Usage Tracker probably won't work seamlessly for a Dataverse installation.

**Comment by cmbz** [comment]
2024/01/03: Closing, work will be tracked here: https://github.com/IQSS/dataverse-pm/issues/118
