### ISSUE TITLE
NIH AIM:1 YR:2 TASK:2 | 2.1.2 | MVP for integration the repository with computation (NERC)

### ISSUE THREAD

**Issue by mreekie** [IQSS/dataverse-pm#52]
Discuss with Leonid and Jim how we might be able to access Dataverse from a computing resource. e.g. from something running on NERC or FAS Cannon.

┆Issue is synchronized with this [Smartsheet row](https://app.smartsheet.com/sheets/3PXV7GPQcQ769PMhmJvPGr5RcCmgG65VgmFHJv21?rowId=2319070213918596) by [Unito](https://www.unito.io)

**Comment by cmbz** [comment]
Updated title from "**NIH AIM:1 YR:2 TASK:2B | 2.1.2B** | MVP for integration the repository with computation (NERC)" to "**NIH AIM:1 YR:2 TASK:2B | 2.1.2** | MVP for integration the repository with computation (NERC)"

**Comment by mreekie** [comment]
The technological issues surround a UI accessing slow tape backups on NERC has not been solved. However, we now have the US census data incoming and that will drive work on this. NIH also suggested we investigate the use of their strides program to fund storage costs.

**Comment by cmbz** [comment]
2024/01/03: Closing; work will continue to be tracked here: https://github.com/IQSS/dataverse-pm/issues/141
