### ISSUE TITLE
NIH AIM:2 YR:2 TASK:1 | 2.2.1 | Design and implement support for DDI-CDI

### ISSUE THREAD

**Issue by mreekie** [IQSS/dataverse-pm#53]
new

┆Issue is synchronized with this [Smartsheet row](https://app.smartsheet.com/sheets/3PXV7GPQcQ769PMhmJvPGr5RcCmgG65VgmFHJv21?rowId=8480416622137220) by [Unito](https://www.unito.io)

**Comment by mreekie** [comment]
This issue represents a deliverable funded by the NIH
This deliverable supports the [NIH Initiative to Improve Access to NIH-funded Data](https://datascience.nih.gov/news/nih-office-of-data-science-strategy-announces-new-initiative-to-improve-data-access)

Aim 2: Increase support for biomedical and cross-domain metadata standards and controlled vocabularies

One of the useful characteristics of the Dataverse open-source software is its extensive support for metadata standards and additional custom metadata. 

The standards currently supported include:
- The Data Documentation Initiative (DDI), 
- Dublin Core, 
- DataCite, and 
- Schema.org. 

In particular, DDI makes a Dataverse repository interoperable even at the variable/attribute level since it supports variable descriptive and statistical metadata. This allows data exploration and analysis tools to integrate easily with the repository and discovery engines to find variable information. 

In this project, we propose to 
1. expand DDI support to include the recently released DDI-Cross-Domain Integration (DDI-CDI) schema
1. build on existing support for biomedical-related standards relevant to NIH-funded research cases, following the recommendations from https://fairsharing.org/
1. expand descriptive and citation metadata to support funding information and related fields, and 
1. integrate with external services to enable  the support of controlled vocabularies for any metadata field, based on standardized, widely used data dictionaries.  The HMS Research Data Management group will participate in the development of these standards and vocabularies for biomedical datasets, working directly with research laboratories. 


Links:
- [NIH OTA document for this work](https://docs.google.com/document/d/1cFK8pdwMKIRZxNs8EZXL1cXmW0ho6Rx9ulCewJ1ZCFI/edit?usp=sharing)
- [Backlog Grooming Board](https://github.com/orgs/IQSS/projects/32/views/13)


Related Deliverables:
[2 | 1.2.2 | Define use cases for DDI-CDI support | 5](https://github.com/orgs/IQSS/projects/32/views/12)
2 | 2.2.1 | Design and implement support for DDI-CDI
2 | 2.2.2 | Define use cases for supporting biomedical metadata standards
2 | 3.2.1 | Design and implement biomedical metadata standards, and add funding related metadata 
2 | 4.2.1 | Assess and improve metadata support

**Comment by mreekie** [comment]
March Report 
(2.2.1) We reviewed and confirmed [a list of metadata fields that the GREI metadata and search WG recommends](https://docs.google.com/spreadsheets/d/1fhsyV_Q92N6AiKUOWuZGvqMYS4pj6pT-) and we commented on the vocabularies that Harvard Dataverse uses, thinks should be used, or has plans to use for particular fields, including using CrossRef's registry of research funders (FundRef) and ROR for organization names. We are continuing to work on issues for the support of FundRef (see [GitHub issue](https://github.com/IQSS/dataverse/issues/9150)) and ROR (see [GitHub issue](https://github.com/IQSS/dataverse/issues/9151)).

**Comment by cmbz** [comment]
Updated title from NIH AIM:2 YR:2 **TASK:1B | 2.2.1B** | Design and implement support for DDI-CDI to NIH AIM:2 YR:2 **TASK:1 | 2.2.1** | Design and implement support for DDI-CDI

**Comment by cmbz** [comment]
2024/01/03: Closing, work continues here: https://github.com/IQSS/dataverse-pm/issues/116
