### ISSUE TITLE
NIH AIM:2 YR:2 TASK:2 | 2.2.2 | Define use cases for supporting biomedical metadata standards

### ISSUE THREAD

**Issue by mreekie** [IQSS/dataverse-pm#54]
new

┆Issue is synchronized with this [Smartsheet row](https://app.smartsheet.com/sheets/3PXV7GPQcQ769PMhmJvPGr5RcCmgG65VgmFHJv21?rowId=3519858244276100) by [Unito](https://www.unito.io)

**Comment by mreekie** [comment]
This issue represents a deliverable funded by the NIH
This deliverable supports the [NIH Initiative to Improve Access to NIH-funded Data](https://datascience.nih.gov/news/nih-office-of-data-science-strategy-announces-new-initiative-to-improve-data-access)

Aim 2: Increase support for biomedical and cross-domain metadata standards and controlled vocabularies

One of the useful characteristics of the Dataverse open-source software is its extensive support for metadata standards and additional custom metadata. 

The standards currently supported include:
- The Data Documentation Initiative (DDI), 
- Dublin Core, 
- DataCite, and 
- Schema.org. 

In particular, DDI makes a Dataverse repository interoperable even at the variable/attribute level since it supports variable descriptive and statistical metadata. This allows data exploration and analysis tools to integrate easily with the repository and discovery engines to find variable information. 

In this project, we propose to 
1. expand DDI support to include the recently released DDI-Cross-Domain Integration (DDI-CDI) schema
1. build on existing support for biomedical-related standards relevant to NIH-funded research cases, following the recommendations from https://fairsharing.org/
1. expand descriptive and citation metadata to support funding information and related fields, and 
1. integrate with external services to enable  the support of controlled vocabularies for any metadata field, based on standardized, widely used data dictionaries.  The HMS Research Data Management group will participate in the development of these standards and vocabularies for biomedical datasets, working directly with research laboratories. 

Other deliverables associated with this one:
2 | 2.2.1 | Design and implement support for DDI-CDI
2 | 2.2.2 | Define use cases for supporting biomedical metadata standards
2 | 3.2.1 | Design and implement biomedical metadata standards, and add funding related metadata
2 | 4.2.1 | Assess and improve metadata support

**Comment by mreekie** [comment]
March Update:

(2.2.2) This activity is waiting for more input from the community although there is ongoing discussion. A meeting last month with Seoul National University, Shout Korea, was centered on harvesting, interoperability and metadata sharing at dataset level.

**Comment by cmbz** [comment]
Updated title from: NIH AIM:2 YR:2 **TASK:2B | 2.2.2B** | Define use cases for supporting biomedical metadata standards to NIH AIM:2 YR:2 **TASK:2 | 2.2.2** | Define use cases for supporting biomedical metadata standards

**Comment by mreekie** [comment]
Grooming/Monthly update meeting.
- Does this deliverable overlap with the work @jggautier is doing on 002.1-002.5? If so, then maybe this deliverable belongs to the 
working subcommittee?  
- This question is related to the larger issue of tracking non-development work and development work in the same context.

**Comment by jggautier** [comment]
The work that the 3 GREI subcommittees I'm involved in - Use Cases, Metadata/Search, Metrics - haven't worked on support for biomedical metadata standards and so far have no plans for this. I'm not sure about the Community Engagement subcommittee.

@sbarbosadataverse is part of the Community Engagement subcommittee. Has that group's work been related to support for biomedical metadata standards?

**Comment by jggautier** [comment]
In [a comment in the Dataverse - 4.2023 - Monthly Technical Status Report](https://docs.google.com/document/d/1J3tl1sM96lBGR893oTVUckcH5I8MXqPn/edit?disco=AAAAwbsXpMY) I wrote that for the May 2023 report we could include some non-development work associated with defining use cases for supporting biomedical metadata standards:

On May 5 I met with a group at Harvard with expertise in describing biomedical research data. The meeting was mostly about to see how we could collaborate with the group, and we agreed to start with defining use cases. I'm waiting to hear back from two of the group's members about their projects.

**Comment by mreekie** [comment]
Update from Julian RE: april - In April there has been no development or non-development work associated with defining use cases for supporting biomedical metadata standards.

**Comment by cmbz** [comment]
2024/01/03: Closing this issue. Work will continue to be tracked here: https://github.com/IQSS/dataverse-pm/issues/149
