### ISSUE TITLE
NIH AIM:2 YR:2 TASK:4 | 2.2.4 | Support Indigenous datasets

### ISSUE THREAD

**Issue by mreekie** [IQSS/dataverse-pm#56]
This is a new task added for Year 2 that was not present in the original OTA.

Initial notes provided by Stefano:
- In order to properly support indigenous data sets, Dataverse need to able to incorporate at least TK (Traditional Knowledge) Labels (https://mukurtu.org/support/traditional-knowledge-labels-faq/) in the metadata fields. 
- Dataverse has already started to work on more general external vocabulary support but in order to fully support TK labels some refactoring is needed. This activity reinforces the efforts around objective "Adopt Consistent Metadata Models".

┆Issue is synchronized with this [Smartsheet row](https://app.smartsheet.com/sheets/3PXV7GPQcQ769PMhmJvPGr5RcCmgG65VgmFHJv21?rowId=2596809642823556) by [Unito](https://www.unito.io)

**Comment by mreekie** [comment]
One of a bunch of dupes from scripting error

**Comment by cmbz** [comment]
2024/01/03: Closing; tracking will continue here: https://github.com/IQSS/dataverse-pm/issues/119
