### ISSUE TITLE
NIH AIM:4 YR:2 TASK:1 | 2.4.1 | Implement packaging standards based on working group feedback

### ISSUE THREAD

**Issue by mreekie** [IQSS/dataverse-pm#57]
new

┆Issue is synchronized with this [Smartsheet row](https://app.smartsheet.com/sheets/3PXV7GPQcQ769PMhmJvPGr5RcCmgG65VgmFHJv21?rowId=7123936027299716) by [Unito](https://www.unito.io)

**Comment by mreekie** [comment]
March Update

(1.4.2, 2.4.1) 1.4.2 related activity was completed at an extent of 50% in year 1 and transferred to year 2. The Dataverse team meets regularly with several actors including other colleagues from the GREI initiative. No formal working group has been yet created.

**Comment by cmbz** [comment]
Updated label from NIH AIM:4 YR:2 TASK:1B | 2.4.1B | Implement packaging standards based on working group feedback to NIH AIM:4 YR:2 TASK:1 | 2.4.1 | Implement packaging standards based on working group feedback

**Comment by cmbz** [comment]
2024/01/03: Closing, work will be tracked here: https://github.com/IQSS/dataverse-pm/issues/146
