### ISSUE TITLE
NIH AIM:6 YR:2 TASK:1 | 2.6.1 | Test differentially private releases with NIH-funded datasets

### ISSUE THREAD

**Issue by mreekie** [IQSS/dataverse-pm#59]
Possible problem statement:  Integration activity is pending OpenDP product work. The plan is to install DP Creator on the same server of HDV. In September we plan to make use of future login capabilities of the SPA for HDV that will simplify the user trust when it comes to manipulate data with DP Creator.

┆Issue is synchronized with this [Smartsheet row](https://app.smartsheet.com/sheets/3PXV7GPQcQ769PMhmJvPGr5RcCmgG65VgmFHJv21?rowId=6319668504514436) by [Unito](https://www.unito.io)

**Comment by mreekie** [comment]
March Update

(2.6.1) The OpenDP team is working on the DP Creator Analyst Mode MVP and we will eventually need to provide integration support. Separately Harvard is still discussing internally about how to handle sensitive data in general.  Harvard has created a committee on regulated data and we are collaborating with this group to move forward.

**Comment by cmbz** [comment]
2024/01/03: Closed; work will be tracked here: https://github.com/IQSS/dataverse-pm/issues/148
