### ISSUE TITLE
NIH AIM:6 YR:2 TASK:2 | 2.6.2 | Design and implement MVP for DataTags levels

### ISSUE THREAD

**Issue by mreekie** [IQSS/dataverse-pm#60]
new

┆Issue is synchronized with this [Smartsheet row](https://app.smartsheet.com/sheets/3PXV7GPQcQ769PMhmJvPGr5RcCmgG65VgmFHJv21?rowId=1470909735980932) by [Unito](https://www.unito.io)

**Comment by cmbz** [comment]
2024/01/03: Closing; work will be tracked here: https://github.com/IQSS/dataverse-pm/issues/148
