### ISSUE TITLE
NIH AIM:7 YR:2 TASK:1 & 2 | 2.7.1 & 2.7.2 | UI related work

### ISSUE THREAD

**Issue by mreekie** [IQSS/dataverse-pm#61]
|Task | Aim | Description|
|----|----|----|
|2.7.1 | 7 | Research and design of UI modules for creating datasets and supporting publishing workflows|
|2.7.2 | 7  | Implementation of UI modules for creating datasets and supporting publishing workflows|

For year two we are going to stay the course with the SPA creation with the aim of satisfying these deliverables.

┆Issue is synchronized with this [Smartsheet row](https://app.smartsheet.com/sheets/3PXV7GPQcQ769PMhmJvPGr5RcCmgG65VgmFHJv21?rowId=43967249862532) by [Unito](https://www.unito.io)

**Comment by mreekie** [comment]
First draft to start March 2023 update

(2.7.1, 2.7.2) This activity was completed at an extent of 92% in year 1 and transferred to year 2. The Authentication/Authorization, and UI Modularity working groups are meeting regularly and working on their proposals. Prototyping continues and has reached the point where the dev process is being integrated so that it is not stand-alone. A document describing an MVP for the new Dataverse frontend is in preparation. A document about current Dataverse modularization has been produced though not yet publicly released. Most of the grounding work has been completed,  though this activity will continue in year 2 and tracked through the corresponding deliverables.

**Comment by mreekie** [comment]
First draft to start March 2023 update

(2.7.1, 2.7.2) This activity was completed at an extent of 92% in year 1 and transferred to year 2. The Authentication/Authorization, and UI Modularity working groups are meeting regularly and working on their proposals. Prototyping continues and has reached the point where the dev process is being integrated so that it is not stand-alone. A document describing an MVP for the new Dataverse frontend is in preparation. A document about current Dataverse modularization has been produced though not yet publicly released. Most of the grounding work has been completed,  though this activity will continue in year 2 and tracked through the corresponding deliverables.

**Comment by cmbz** [comment]
Fixed typo in title: duplicated 2.7.1 -> 2.7.2

**Comment by cmbz** [comment]
2024/01/03: Closing, work will be tracked here: https://github.com/IQSS/dataverse-pm/issues/123
