### ISSUE TITLE
NIH AIM:2 YR:2 TASK:3 | 2.2.3 | Support Multiple DataCite Providers

### ISSUE THREAD

**Issue by mreekie** [IQSS/dataverse-pm#62]
This is a new task added for Year 2 that was not present in the original OTA.

Initial notes provided by Stefano:

- In order to support multiple DataCite providers, Dataverse software need to implement a new mechanism to allow the multiple providers to be registered dynamically and increase flexibility to point to the right PID (persistent identifier) provider. There are use cases where an account that uses one authority/shoulder can also manage/edit PIDs with other authorities that have been individually transferred to that account at DataCite.
- There is also the need to allow for the default PID provider to be selected per collection.

┆Issue is synchronized with this [Smartsheet row](https://app.smartsheet.com/sheets/3PXV7GPQcQ769PMhmJvPGr5RcCmgG65VgmFHJv21?rowId=1402224618983300) by [Unito](https://www.unito.io)

**Comment by cmbz** [comment]
2024/01/03: Closing. Work will be tracked here: https://github.com/IQSS/dataverse-pm/issues/132
