### ISSUE TITLE
NIH AIM:8 YR:2 TASK:1 | 2.8.1 | Design and create new data curation services focused on biomedical metadata

### ISSUE THREAD

**Issue by mreekie** [IQSS/dataverse-pm#63]
new

┆Issue is synchronized with this [Smartsheet row](https://app.smartsheet.com/sheets/3PXV7GPQcQ769PMhmJvPGr5RcCmgG65VgmFHJv21?rowId=4333272436789124) by [Unito](https://www.unito.io)

**Comment by cmbz** [comment]
2024/01/03: Closing, work will be tracked here: https://github.com/IQSS/dataverse-pm/issues/149
