### ISSUE TITLE
NIH AIM:8 YR:2 TASK:2 | 2.8.2 | Outreach, training, including session on Generalist repositories during the Dataverse Community meeting (year 2)

### ISSUE THREAD

**Issue by mreekie** [IQSS/dataverse-pm#64]
This NIH deliverable is in Sonia's Bailiwick.
She updates the activities here monthly for the NIH report.
[reports directory here](https://drive.google.com/drive/folders/0ACthvafpCn06Uk9PVA)

┆Issue is synchronized with this [Smartsheet row](https://app.smartsheet.com/sheets/3PXV7GPQcQ769PMhmJvPGr5RcCmgG65VgmFHJv21?rowId=5974509363351428) by [Unito](https://www.unito.io)

**Comment by mreekie** [comment]
Sonia's notes on April 2023 update.
1. The GREI proposal to open repo was not accepted
2. TK Labels and Dataverse integration proposal was accepted for open repo
3. Curating big data in Dataverse proposal was accepted for open repo
4. Dataverse integration with DSpace from Harvard Data Commons objectives was accepted for open repo
5. Modularity and Dataverse was accepted for open repo
6. Dataverse for curating and managing data was accepted for open repo


April, 2023:
Dataverse participated at csv,conf,v7 with a collaborative workshop on Curating Data in Dataverse, Datacite, Borealis Dataverse Consortium, and  CIMMYT Dataverse, and a presentation on Dataverse and PIDs

Demo on TK Label support was done with IDS support working group and video uploaded to DataverseTV and shared with Ishwar: [https://drive.google.com/file/d/1kWMdMDlqm-kDK5yexBqKhaYuPBgefZD6/view](https://www.google.com/url?q=https://drive.google.com/file/d/1kWMdMDlqm-kDK5yexBqKhaYuPBgefZD6/view&sa=D&source=docs&ust=1683635065747361&usg=AOvVaw3kQ9yWc9pXdVShnqGxrRUm)

**Comment by cmbz** [comment]
2024/01/03: Closing, work will be tracked here: https://github.com/IQSS/dataverse-pm/issues/122
