### ISSUE TITLE
Retrospective: 4-12-23 Start: giving a point count of finished issues each sprint 

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse-pm#68]
Start: (SK) giving a point count of finished issues each sprint (KC) (EK)

From: https://docs.google.com/document/d/1TVS7eJo5koPbK39QP_0N8IPk_Wp6JQSvCaMQl0LLBBI/edit

**Comment by cmbz** [comment]
@mreekie Would you add your table from the 2023/04/26 sprint kickoff meeting here?
