### ISSUE TITLE
Retrospective: 4-12-23 Keep: Working on containerizing (Dockerizing) Dataverse 

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse-pm#71]
Keep: X (PD) Working on containerizing (Dockerizing) Dataverse (EK,LA, PD, KC)
From: https://docs.google.com/document/d/1TVS7eJo5koPbK39QP_0N8IPk_Wp6JQSvCaMQl0LLBBI/edit

Note: Although a keep, not sure whether there might be action items related to this: make containerization part of road map, produce plan, prioritize/gain approval, etc Perhaps this has already happened, in which case, communicate decisions and activities.

**Comment by cmbz** [comment]
Related to containerization:
- Discussion of the [Containerization Proposal](https://docs.google.com/document/d/14DHDB24Cp_kzpYqhHCKCtnzOw8_WuLOOONyqJHSsaYM/edit) will occur during the 3 May Dataverse Project Monthly Meeting.

**Comment by pdurbin** [comment]
We'll have another meeting tomorrow! https://ct.gdcc.io

/cc @poikilotherm @GPortas
