### ISSUE TITLE
NIH AIM:1 YR:2 TASK:1.1.1  | 2.1.1B | (started yr1) Minimum Viable Product (MVP) for registering metadata in the repository and connecting the metadata to the data in the research computing remote storage (NESE), including Globus endpoints

### ISSUE THREAD

**Issue by mreekie** [IQSS/dataverse-pm#80]
┆Issue is synchronized with this [Smartsheet row](https://app.smartsheet.com/sheets/3PXV7GPQcQ769PMhmJvPGr5RcCmgG65VgmFHJv21?rowId=7643791602175876) by [Unito](https://www.unito.io)

**Comment by mreekie** [comment]
March update 

(2.1.1) This activity was completed at an extent of 90% in year 1 and
transferred to year 2. Planning continues around supporting the Globus
endpoint for Dataverse at the Northeast Storage Exchange (NESE) and
moving beyond the MVP. The MVP enables connection from Harvard
Dataverse to the Globus endpoint and storage but does not support real
time browsing for large files yet due to specific technological characteristics
of tape support. Technical plan for this last step is anchored in issue 9123.
This activity will be performed in the first half of year 2, as the necessary
development resources have been identified.

**Comment by cmbz** [comment]
Closing:
- https://github.com/IQSS/dataverse/issues/9123 in 6.1 completes this task
