### ISSUE TITLE
NIH AIM:2 YR:2 TASK:1B | 2.2.1B | (cont from yr 1: 1.2.1) Design and implement integration with controlled vocabularies

### ISSUE THREAD

**Issue by mreekie** [IQSS/dataverse-pm#83]
Continuation of:

* https://github.com/IQSS/dataverse-pm/issues/7

┆Issue is synchronized with this [Smartsheet row](https://app.smartsheet.com/sheets/3PXV7GPQcQ769PMhmJvPGr5RcCmgG65VgmFHJv21?rowId=3997036171972484) by [Unito](https://www.unito.io)

**Comment by cmbz** [comment]
Updated title from NIH AIM:2 YR:2 **TASK:1A | 2.2.1A** | (cont from yr 1: 1.2.1) Design and implement integration with controlled vocabularies to NIH AIM:2 YR:2 TASK:1B | 2.2.1B | (cont from yr 1: 1.2.1) Design and implement integration with controlled vocabularies

**Comment by cmbz** [comment]
For remaining tasks to complete before 2.1.1B can be considered complete: 
- See comment on related issue: https://github.com/IQSS/dataverse-pm/issues/7#issuecomment-1454151951 
- See related issue: https://github.com/IQSS/dataverse/issues/9151
- Specifically, see comment: https://github.com/IQSS/dataverse/issues/9151#issuecomment-1572710674

**Comment by cmbz** [comment]
**2024/01/03**
- Upon review of the tangled web of related issues, there appears that there is only one issue remaining related to this task: https://github.com/IQSS/dataverse/issues/9151
- Therefore, I am closing this particular issue.
