### ISSUE TITLE
NIH AIM:2 YR:2 TASK:2B  | 2.2.2B | (Started yr 1) Define use cases for DDI-CDI support

### ISSUE THREAD

**Issue by mreekie** [IQSS/dataverse-pm#84]
Continues work from:

* https://github.com/IQSS/dataverse-pm/issues/6

┆Issue is synchronized with this [Smartsheet row](https://app.smartsheet.com/sheets/3PXV7GPQcQ769PMhmJvPGr5RcCmgG65VgmFHJv21?rowId=2532216235052932) by [Unito](https://www.unito.io)

**Comment by cmbz** [comment]
2024/01/03: Closed; additional work will be tracked here: https://github.com/IQSS/dataverse-pm/issues/116
