### ISSUE TITLE
NIH AIM:4 YR:2 TASK:1B | 2.4.1B | (started yr1) Resolve OAI-PMH harvesting issues

### ISSUE THREAD

**Issue by mreekie** [IQSS/dataverse-pm#85]
Continuation of: https://github.com/IQSS/dataverse-pm/issues/10

**Comment by cmbz** [comment]
Updated title from NIH AIM:4 YR:2 **TASK:1A | 2.4.1A** | (started yr1) Resolve OAI-PMH harvesting issues to NIH AIM:4 YR:2 **TASK:1B | 2.4.1B** | (started yr1) Resolve OAI-PMH harvesting issues

**Comment by cmbz** [comment]
The following issues identified in [4 | 1.4.1 | Resolve OAI-PMH harvesting issues | 5](https://github.com/IQSS/dataverse-pm/issues/10#top) #10 remain open:
- [Refactor the OAI code, Step 2 #8842](https://github.com/IQSS/dataverse/issues/8842)
- [Revisit/reimplement the concept of a "Harvested file" dataverse#8629](https://github.com/IQSS/dataverse/issues/8629)
- [Harvest: Set export can temporarily be adversely affected by full (clean) reindex. #3437](https://github.com/IQSS/dataverse/issues/34370)
- [Harvest: Do not list a set as available in ListSets until it has been successfully exported at least once. #3322](https://github.com/IQSS/dataverse/issues/3322)
- [Feature Request/Idea: Sanitize languages controlled vocabulary values #8243](https://github.com/IQSS/dataverse/issues/8243)
- [Harvesting: OAI sets are not updated when datasets are deleted. #8005](https://github.com/IQSS/dataverse/issues/8005)
- [Remaining mapping problems when harvesting from a repository using ISO 639-3 language codes #8578](https://github.com/IQSS/dataverse/issues/8578)

**Comment by pdurbin** [comment]
Perhaps we could fix this one too:

- https://github.com/IQSS/dataverse/issues/9275

**Comment by cmbz** [comment]
@pdurbin Happy to add to bottom of prioritized list, [here](https://github.com/IQSS/dataverse-pm/issues/85#issuecomment-1572971317), but wary of taking on too much given that this task was slated for completion last year and has carried over. See original curated list [here](https://github.com/IQSS/dataverse-pm/issues/10#issue-1609274694), for background.

**Comment by jggautier** [comment]
Hey @cmbz, here are those GitHub issues that I was referring to and you asked me to list here when we were Slacking with @landreev today. And below each issue I added the related email conversations with admins of other repositories.

1. https://github.com/IQSS/dataverse.harvard.edu/issues/92
  - https://help.hmdc.harvard.edu/Ticket/Display.html?id=324230
  - https://help.hmdc.harvard.edu/Ticket/Display.html?id=329544
2. https://github.com/IQSS/dataverse.harvard.edu/issues/142
  - https://help.hmdc.harvard.edu/Ticket/Display.html?id=314258
3. https://github.com/IQSS/dataverse.harvard.edu/issues/153
  - https://help.hmdc.harvard.edu/Ticket/Display.html?id=314258
4. https://github.com/IQSS/dataverse.harvard.edu/issues/172
  - https://help.hmdc.harvard.edu/Ticket/Display.html?id=322153
6. https://github.com/IQSS/dataverse/issues/7624
  - https://help.hmdc.harvard.edu/Ticket/Display.html?id=287243

I think the second GitHub issue, https://github.com/IQSS/dataverse.harvard.edu/issues/142, is a duplicate and more specific version of the third GitHub issue, https://github.com/IQSS/dataverse.harvard.edu/issues/153, so maybe the second one can be closed?

**Comment by cmbz** [comment]
**2024/01/29**
- I have moved all the remaining, open harvesting issues mentioned here to the following epic for tracking: https://github.com/IQSS/dataverse-pm/issues/171
- Please follow the new epic for updates about the individual issues.
