### ISSUE TITLE
NIH AIM:4 YR:2 TASK:2B |  2.4.2B | Create working group on packaging standards to share metadata and data across repositories

### ISSUE THREAD

**Issue by mreekie** [IQSS/dataverse-pm#86]
This issue is the continuation of:

* https://github.com/IQSS/dataverse-pm/issues/12

┆Issue is synchronized with this [Smartsheet row](https://app.smartsheet.com/sheets/3PXV7GPQcQ769PMhmJvPGr5RcCmgG65VgmFHJv21?rowId=8832832418828164) by [Unito](https://www.unito.io)

**Comment by cmbz** [comment]
2024/01/03: Closing, work will be tracked here: https://github.com/IQSS/dataverse-pm/issues/146
