### ISSUE TITLE
NIH AIM:5 YR:2 TASK:1B  | 2.5.1B | Standardize download metrics for the Harvard Dataverse repository following Make Data Count

### ISSUE THREAD

**Issue by mreekie** [IQSS/dataverse-pm#87]
This issue continues work on:

* https://github.com/IQSS/dataverse-pm/issues/8

┆Issue is synchronized with this [Smartsheet row](https://app.smartsheet.com/sheets/3PXV7GPQcQ769PMhmJvPGr5RcCmgG65VgmFHJv21?rowId=8525185522028420) by [Unito](https://www.unito.io)

**Comment by cmbz** [comment]
Updated title from NIH AIM:5 YR:2 **TASK:1B | 2.5.1B** | Standardize download metrics for the Harvard Dataverse repository following Make Data Count to NIH AIM:5 YR:2 TASK:1 | 2.5.1 | Standardize download metrics for the Harvard Dataverse repository following Make Data Count

**Comment by cmbz** [comment]
2024/01/03: Closing, work will be tracked here: https://github.com/IQSS/dataverse-pm/issues/118
