### ISSUE TITLE
NIH AIM:5 YR:2 TASK:2B | 2.5.2B | Collaborate with other repositories to follow Make Data Count recommendations

### ISSUE THREAD

**Issue by mreekie** [IQSS/dataverse-pm#90]
Continuation of:

* https://github.com/IQSS/dataverse-pm/issues/89

┆Issue is synchronized with this [Smartsheet row](https://app.smartsheet.com/sheets/3PXV7GPQcQ769PMhmJvPGr5RcCmgG65VgmFHJv21?rowId=1749214496247684) by [Unito](https://www.unito.io)

**Comment by cmbz** [comment]
Updated title from NIH AIM:5 YR:2 **TASK:2A | 2.5.2A** | Collaborate with other repositories to follow Make Data Count recommendations to NIH AIM:5 YR:2 **TASK:2B | 2.5.2B** | Collaborate with other repositories to follow Make Data Count recommendations

**Comment by cmbz** [comment]
2024/01/03: Closing, work will be tracked here: https://github.com/IQSS/dataverse-pm/issues/118
