### ISSUE TITLE
NIH AIM:6 YR:2 TASK:1B  | 2.6.1B | Integrate with OpenDP tools to support differentially private statistical releases of de-identified data deposited in the repository 

### ISSUE THREAD

**Issue by mreekie** [IQSS/dataverse-pm#91]
Continuation of:

* https://github.com/IQSS/dataverse-pm/issues/5

┆Issue is synchronized with this [Smartsheet row](https://app.smartsheet.com/sheets/3PXV7GPQcQ769PMhmJvPGr5RcCmgG65VgmFHJv21?rowId=5914891733913476) by [Unito](https://www.unito.io)

**Comment by cmbz** [comment]
Updated title fro NIH AIM:6 YR:2 **TASK:1A | 2.6.1A** | Integrate with OpenDP tools to support differentially private statistical releases of de-identified data deposited in the repository to NIH AIM:6 YR:2 **TASK:1B | 2.6.1B** | Integrate with OpenDP tools to support differentially private statistical releases of de-identified data deposited in the repository

**Comment by cmbz** [comment]
2024/01/03: Closed, work will be tracked here: https://github.com/IQSS/dataverse-pm/issues/148
