### ISSUE TITLE
NIH AIM:6 YR:2 TASK:2B | 2.6.2B | Discovery phase to support DataTags

### ISSUE THREAD

**Issue by mreekie** [IQSS/dataverse-pm#92]
Continuation of:

* https://github.com/IQSS/dataverse-pm/issues/9

┆Issue is synchronized with this [Smartsheet row](https://app.smartsheet.com/sheets/3PXV7GPQcQ769PMhmJvPGr5RcCmgG65VgmFHJv21?rowId=140257201704836) by [Unito](https://www.unito.io)

**Comment by cmbz** [comment]
Updated title from NIH AIM:6 YR:2 **TASK:2A | 2.6.2A** | Discovery phase to support DataTags to NIH AIM:6 YR:2 **TASK:2B | 2.6.2B** | Discovery phase to support DataTags
