### ISSUE TITLE
Transition to a projectV2 project board

### ISSUE THREAD

**Issue by mreekie** [IQSS/dataverse-pm#96]
**Proposed transition:**
- communicate to the community prior
- Upgrade on a Friday
- As part of the upgrade, drop all closed issues older than 90? days
- After the upgrade test the automations.
- After the upgrade make sure the external mike reporting scripts 
- Pick a Friday in June
  -  after the community meeting during the summer vacation lull.

**Risks:**
- Broken automations
  - trivial to fix
- Broken reporting scripts
  - will be a test plan
- community developer confusion
  - communication (e.g., see issue identify by Phil: https://github.com/IQSS/dataverse/issues/9157)
- Service Interruption
  - doing it after the comm. meeting during the summer slow months

**Benefits:**
- reporting will be simplified
- more information can be shown on the same board in a simpler manner.
- GitHub is pushing the upgrade

**Comment by pdurbin** [comment]
Related:

- https://github.com/IQSS/dataverse/issues/9157

**Comment by mreekie** [comment]
Closing #7  as a dupe of this so I'm copying the relevant info
We started today playing around with different possibilities using this project:
https://github.com/orgs/IQSS/projects/48/

**Comment by mreekie** [comment]
July 12th is the next dataverse project meeting.
Let's use that date as the target for sharing this idea/proposal with the team.
Then the execution date would be set for August 16th

**Comment by mreekie** [comment]
Met with Ceilyn today and showed her how things are working for the Engineering Team Sid board.
After, I created a flowchart of how we can implement it.
As we talked about it I realized that there is one big difference between the DV workflow and the engineering team and that it might be an problem

PRs
- The eng team does not introduce PRs onto the board.
- When automation introduces a new PR onto the board it does not include setting the value of the BacklogQ field. It only modifies the value of the "Status" field. 
  - in order for an item to appear on the sprint board in this scheme, it needs:
      - status: to be set to a value
      - BacklogQ: to be set to an equivalent to "Prioritized"

**Comment by mreekie** [comment]
I need to think more on this. Is there still a value add here?
In the meantime, I put thoughts on paper for how we would need to transition if it did work fine with PRs. on a miro board.
https://miro.com/app/board/uXjVMtgIhAM=/?share_link_id=568090538464

**Comment by mreekie** [comment]
We may be able to do this with github actions.
It may be time to look at GitHub Actions.
https://docs.github.com/en/actions/managing-issues-and-pull-requests/using-github-actions-for-project-management
I'll take a look

**Comment by mreekie** [comment]
Ceilyn/Mike discussiontoday:
The reason I'm bringing this up now is that the sprint board is becoming "unusable" -- super slow, very laggy. I'm thinking that it has to do with 1) too many Done items, and 2) maybe just time to migrate.


Mike Reekie
  [13:48](https://iqss.slack.com/archives/D0511UUB3SR/p1694195303061939)
hmmm.... That raises an approach...
Just migrate the Items on the current sprint board.
Then we can keep going on the combining the boards in the background.
:bangbang:
1

[13:49](https://iqss.slack.com/archives/D0511UUB3SR/p1694195342222099)
We remove all issues in the done column first that are older than I dunno - 3? months old.

[13:50](https://iqss.slack.com/archives/D0511UUB3SR/p1694195450670899)
I could work on that this afternoon.
- Retrieve a list of all items in the done column.
- Remove all items that were closed < 3 months ago from the list.
- Remove the resulting list of items from the current sprint board

Next Step:
- [ ] propose a list of issues to be removed from the current sprint project board, which have the status closed.

**Comment by mreekie** [comment]
Notes:
- There are multiple repositories represented in the closed state in the https://github.com/orgs/IQSS/projects/2 project. For this step the objective is to drastically trimming down the issues in the project.  Most of the issues in the project come from thi s repo: https://github.com/IQSS/dataverse/issues.  I'm only going to consider that repo.

**Comment by mreekie** [comment]
Transitioned this to a use case in the active rep/project
[Transition to a projectV2 project board#52](https://github.com/thisaintwork/iqss_gh_reporting/issues/52)
